### PR TITLE
Refix the model that has been reverted in common lib

### PR DESCRIPTION
**Pull request by elayabharath**
https://github.com/larksystems/katikati_common_lib/commit/7d831b8a6da0fc99311d385731ce56375c883242

### CODE REVIEW

**Comment by marianamarasoiu** [comment]
@danrubel can I ask you to take a look at this? Is the engine exporting `TagType.normal` or `TagType.Normal`?

**Comment by danrubel** [comment]
@marianamarasoiu Yes this looks correct as I have reverted my earlier work for now
         (see https://github.com/larksystems/katikati_common_lib/pull/62)

@elayabharath Sorry about forgetting to revert nook and thank you for fixing!

**Review by danrubel — APPROVED** [review]
LGTM!

**Review by marianamarasoiu — APPROVED** [review]
Ah, got it, sorry for the noise, I forgot that `TagType` is a class not an enum, and its values are explicitly matched to lowercase strings.

Thanks @danrubel  and @elayabharath - LGTM from me as well then!

**Pull request merged**
